### ISSUE TITLE
CI/CD support

### ISSUE THREAD

**Issue by rfranzke** [gardener/hyperkube#1]
Today, there is no automatism that would regularly check for new Kubernetes versions and trigger the build/release for this repository.

The reasons are mainly listed in https://github.com/gardener/hyperkube/blob/master/README.md#limitations.

Ideally, we can have two CI scripts:

* The first one runs regularly (e.g., every 10min) and checks whether there are new Kubernetes versions that we have not built yet. For those versions it could checkout a branch from `master`, write the respective version to the `KUBERNETES_VERSION` file, commit and push this branch.
* The second script reacts on `release-*` branches and builds the `Dockerfile`, pushes the image to GCR, and then deletes the branch again.

Parts are already implemented in `.ci/check-and-release`.

**Comment by timebertt** [comment]
@AndreasBurger any updates on this?

**Comment by AndreasBurger** [comment]
From my point of view this issue can be closed. I've created a Concourse-Pipeline that runs the `.ci/check-and-release` script hourly (that does seem to fulfill the requirements stated above) and we were able to verify that the built images here behave as expected.
There is also a Component-Descriptor published, but as far as I know it is not yet referenced anywhere else.

**Comment by rfranzke** [comment]
OK, thanks!
/close
