### ISSUE TITLE
hyperkube download fails for new kubernetes patches, and older kubernetes versions will fail with new gardener

### ISSUE THREAD

**Issue by lotharbach** [gardener/hyperkube#12]
**How to categorize this issue?**

/area delivery
/kind bug

**What happened**:
gardener/gardener#8968 changes the default hyperkube image registry to europe-docker.pkg.dev

The last round of kubernetes/hyperkube patches was only uploaded to europe-docker.pkg.dev, so those won't work with gardener 1.86.1 or any older versions that still try to pull from eu.gcr.io

Most older kubernetes/hyperkube versions are not yet uploaded to europe-docker.pkg.dev, so those won't work with main or gardener 1.87.0

**What you expected to happen**:
All still supported kubernetes/hyperkube versions to be available in both registries, or an default imageVector that deals with this temporary dualism and points different versions to different registries.

**How to reproduce it (as minimally and precisely as possible)**:
Add kubernetes 1.28.6 to cloudprofile with gardener 1.86.1

Or

Use kubernetes 1.28.5 in cloudprofile with gardener main (Not tested that myself, but you get the idea)

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.85.1

**Comment by ccwienk** [comment]
@rfranzke : I think there are two options at hand:
- extend existing image-replication-job to upload to both GCR and AR
- manually replicate missing images as a temporary workaround (will be required until 1.86.x will reach eol)

As for older k8s / hyperkube versions for gardener-1.87+: is there a way to determine all necessary images/tags? I think it should be sufficient to replicate those from AR -> GCR as a one-off (new versions will be covered by existing pipeline, so this should be a one-off).

**Comment by rfranzke** [comment]
I don't think there is a way to detect which tags are necessary, but I would simply upload all images for Kubernetes 1.20.0 and above - this should be good for now (older versions were deprecated and removed a longer while ago already).

**Comment by ccwienk** [comment]
I think it will be the easiest approach to add another replication-step that will check for all tags in artifact-registry, and replicate _all_ with a tag >= 1.20 back to GCR for the time being
