### ISSUE TITLE
Create new Release for K8s Patch releases

### ISSUE THREAD

**Issue by christianhuening** [gardener/hyperkube#6]
**What would you like to be added**:
I'd kindly like to ask for a new release including the latest k8s patch releases
**Why is this needed**:
To satisfy the update god

**Comment by ialidzhikov** [comment]
New patch versions are available:
- https://github.com/gardener/hyperkube/releases/tag/v1.22.4
- https://github.com/gardener/hyperkube/releases/tag/v1.21.7
- https://github.com/gardener/hyperkube/releases/tag/v1.20.13

/close
